version: '3.4'

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
  mongodb:
    image: mongo
  rabbitmq: 
    image: rabbitmq:3.11.11-management
  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: src/Services/Products/ESourcing.Products/Dockerfile
  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: src/Services/Sourcing/ESourcing.Sourcing/Dockerfile

  esourcing.order:
    image: ${DOCKER_REGISTRY-}esourcingorder
    build:
      context: .
      dockerfile: src/Services/Order/ESourcing.Order/Dockerfile

